{
 "title": "Vibration & Temperature Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "machine",
    "query": "from(bucket: \"vibration_monitoring\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vibration_reading\")\n  |> keep(columns: [\"id\"])\n  |> distinct(column: \"id\")\n  |> filter(fn: (r) => r[\"id\"] != \"null\")\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "title": "RMS Acceleration | ${machine}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"vibration_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vibration_reading\")\n  |> filter(fn: (r) => r[\"_field\"] == \"acceleration\")\n    |> filter(fn: (r) => r[\"id\"] == \"${machine}\")\n\n  "
    }
   ]
  },
  {
   "title": "Peak Frequency | ${machine}",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vibration_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vibration_reading\")\n  |> filter(fn: (r) => r[\"_field\"] == \"peakFrequency\")\n  |> filter(fn: (r) => r[\"id\"] == \"${machine}\")\n\n  "
    }
   ]
  },
  {
   "title": "Temperature | ${machine}",
   "type": "stat",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"vibration_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vibration_reading\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"id\"] == \"${machine}\")\n\n  "
    }
   ]
  },
  {
   "title": "Fourier Transform | ${machine}",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"vibration_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fft\")\n  |> filter(fn: (r) => r[\"id\"] == \"${machine}\")\n  |> drop(columns: [\"id\", \"_measurement\", \"_field\"])\n  |> map(fn: (r) => ({ r with frequency: string(v: r.frequency) + \" Hz\" }))\n\n\n\n\n  "
    }
   ]
  }
 ]
}