version: "2"

services:
    ai_app:
        extends:
            file: ai_analysis/app.yml
            service: api_service
        restart: unless-stopped
        logging:
            driver: syslog
        networks:
            internal:
                aliases:
                    - ml-service.docker.local
    ai_worker:
        extends:
            file: ai_analysis/app.yml
            service: ml_worker
        restart: unless-stopped
        logging:
            driver: syslog
        networks:
            internal:
                aliases:
                    - ml-worker.docker.local
    redis:
        extends:
            file: ai_analysis/app.yml
            service: redis
        restart: unless-stopped
        logging:
            driver: syslog
        networks:
            internal:
                aliases:
                    - redis.docker.local
    mqtt_broker:
        extends:
            file: mqtt_broker/app.yml
            service: app
        restart: unless-stopped
        logging:
            driver: syslog
            options:
                tag: docker-mqtt-broker
        networks:
            internal:
                aliases:
                    - mqtt.docker.local
    timeseries-db:
        extends:
            file: timeseries_sds/app.yml
            service: db
        networks:
            internal:
                aliases:
                    - timeseries-db.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-db
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
    timeseries-db-input:
        extends:
            file: timeseries_sds/app.yml
            service: telegraf
        networks:
            internal:
                aliases:
                    - timeseries-input.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-timeseries-input
        restart: unless-stopped
        depends_on:
            - "timeseries-db"
            - "mqtt_broker"
    dashboard:
        extends:
            file: dashboard_ui/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - dashboard-ui.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-dashboard-ui
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
    kapacitor:
        extends:
            file: kapacitor/app.yml
            service: kapacitor
        restart: unless-stopped
        logging:
            driver: syslog
            options:
                tag: docker-kapacitor
        networks:
            internal:
                aliases:
                    - kapacitor.docker.local
    # chronograf:
    #     extends:
    #         file: ai_analysis/app.yml
    #         service: chronograf
    #     restart: unless-stopped
    #     logging:
    #         driver: syslog
    #         options:
    #             tag: docker-chronograf
    #     networks:
    #         internal:
    #             aliases:
    #                 - chronograf.docker.local   
networks:
     internal:
         name: shoestring-internal
